backend:
  name: github
  repo: maxmatrix5757/Maxmatrix
  branch: main
  base_url: https://ais-dev-a5mhlgv5nxcc73jqzto2hb-349983386831.asia-southeast1.run.app
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
